HuashanCRM/Areas/GoX/Controllers/ReturnGoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using System.Web.UI.DataVisualization.Charting;
using System.Drawing;
using System.Text;
using System.IO;
using Mith.Models;
using Mith.Areas.GoX.Models;

namespace Mith.Areas.GoX.Controllers
{
    public class ReturnGoodsController : CategoryController
    {
        int fun_id = 13;

        #region 首頁
        [MyAuthorize(Com = Competence.Read, function = "退貨資料")]
				public ActionResult Index_Mith(string keyword = "", int Search_LogisticsStatus = 0,int Search_AgreeRefund = 0, int Search_NotLogisticsSN = 0, int Search_CompanyId = 0, DateTime? CreateTime_St = null, DateTime? CreateTime_End = null, int p = 1, int show_number = 8)
        {
            ReturnGoodsModel data = new ReturnGoodsModel();
            var fun = FunctionModel.Get_One(fun_id);
            string get = "";
            if (keyword != "")
            {
                data.Keyword = keyword;
                ViewData["keyword"] = keyword;
                get += Method.Get_URLGet("keyword", keyword);
            }
						if (Search_LogisticsStatus != 0)
            {
							data.Search_LogisticsStatus = Search_LogisticsStatus;
							ViewData["Search_LogisticsStatus"] = Search_LogisticsStatus;
							get += Method.Get_URLGet("Search_LogisticsStatus", Search_LogisticsStatus.ToString());
            }
            if (Search_AgreeRefund != 0)
            {
                data.Search_AgreeRefund = Search_AgreeRefund;
                ViewData["Search_AgreeRefund"] = Search_AgreeRefund;
                get += Method.Get_URLGet("Search_AgreeRefund", Search_AgreeRefund.ToString());
            }
            if (Search_NotLogisticsSN != 0)
            {
                data.Search_NotLogisticsSN = Search_NotLogisticsSN;
                ViewData["Search_NotLogisticsSN"] = Search_NotLogisticsSN;
                get += Method.Get_URLGet("Search_NotLogisticsSN", Search_NotLogisticsSN.ToString());
            }
            if (Search_CompanyId > 0)
            {
                data.Search_CompanyId = Search_CompanyId;
                ViewData["Search_CompanyId"] = Search_CompanyId;
                get += Method.Get_URLGet("Search_CompanyId", Search_CompanyId.ToString());
            }
            if (CreateTime_St != null)
            {
                data.CreateTime_St = CreateTime_St;
                ViewData["CreateTime_St"] = CreateTime_St;
                get += Method.Get_URLGet("CreateTime_St", CreateTime_St.Value.ToString("yyyy/MM/dd HH:mm:ss"));
            }
            if (CreateTime_End != null)
            {
                data.CreateTime_End = CreateTime_End;
                ViewData["CreateTime_End"] = CreateTime_End;
                get += Method.Get_URLGet("CreateTime_End", CreateTime_End.Value.ToString("yyyy/MM/dd HH:mm:ss"));
            }

            ViewBag.Title = fun.Name;
            ViewBag.Title_link = "物流管理 > <a href=\"\">" + fun.Name + "</a>";

            ViewData["p"] = p;
            ViewData["page"] = data.Get_Page(p, show_number);
            ViewData["number"] = show_number;
            ViewData["get"] = get;
            Session["Url"] = Request.Url.AbsoluteUri;
            var Result = data.Get_Data(p, show_number);
            return View(Result);
        }

        [MyAuthorize(Com = Competence.Read, function = "退貨資料")]
				public ActionResult Index_Company(string keyword = "", int Search_LogisticsStatus = 0, int Search_AgreeRefund = 0, int Search_NotLogisticsSN = 0, DateTime? CreateTime_St = null, DateTime? CreateTime_End = null,
            int p = 1, int show_number = 8)
        {
            ReturnGoodsModel data = new ReturnGoodsModel();
            var fun = FunctionModel.Get_One(fun_id);
            string get = "";
            if (keyword != "")
            {
                data.Keyword = keyword;
                ViewData["keyword"] = keyword;
                get += Method.Get_URLGet("keyword", keyword);
            }
						if (Search_LogisticsStatus != 0)
						{
							data.Search_LogisticsStatus = Search_LogisticsStatus;
							ViewData["Search_LogisticsStatus"] = Search_LogisticsStatus;
							get += Method.Get_URLGet("Search_LogisticsStatus", Search_LogisticsStatus.ToString());
						}
            if (Search_AgreeRefund != 0)
            {
                data.Search_AgreeRefund = Search_AgreeRefund;
                ViewData["Search_AgreeRefund"] = Search_AgreeRefund;
                get += Method.Get_URLGet("Search_AgreeRefund", Search_AgreeRefund.ToString());
            }
            if (Search_NotLogisticsSN != 0)
            {
                data.Search_NotLogisticsSN = Search_NotLogisticsSN;
                ViewData["Search_NotLogisticsSN"] = Search_NotLogisticsSN;
                get += Method.Get_URLGet("Search_NotLogisticsSN", Search_NotLogisticsSN.ToString());
            }
            if (CreateTime_St != null)
            {
                data.CreateTime_St = CreateTime_St;
                ViewData["CreateTime_St"] = CreateTime_St;
                get += Method.Get_URLGet("CreateTime_St", CreateTime_St.Value.ToString("yyyy/MM/dd HH:mm:ss"));
            }
            if (CreateTime_End != null)
            {
                data.CreateTime_End = CreateTime_End;
                ViewData["CreateTime_End"] = CreateTime_End;
                get += Method.Get_URLGet("CreateTime_End", CreateTime_End.Value.ToString("yyyy/MM/dd HH:mm:ss"));
            }
            //廠商編號
            data.Search_CompanyId = Mith.Models.Method.Get_CompanyId_Admin(Request.Cookies, Session);

            ViewBag.Title = fun.Name;
            ViewBag.Title_link = "物流管理 > <a href=\"\">" + fun.Name + "</a>";

            ViewData["p"] = p;
            ViewData["page"] = data.Get_Page(p, show_number);
            ViewData["number"] = show_number;
            ViewData["get"] = get;
            Session["Url"] = Request.Url.AbsoluteUri;

            var Result = data.Get_Data(p, show_number);
            return View(Result);
        }

        #endregion

        #region 編輯

        [MyAuthorize(Com = Competence.Update, function = "退貨資料")]
        public ActionResult Edit_Mith(int Id = 0)
        {
            MithDataContext db = new MithDataContext();
            ReturnGoodsModel data = new ReturnGoodsModel();
            var fun = FunctionModel.Get_One(fun_id);

            var item = data.Get_One(Id);
            if (item == null)
            {
                return RedirectToAction("Index_Mith");
            }
            db.Connection.Close();
            ViewBag.Title = "物流管理 > " + fun.Name + " > 詳情 ";
            ViewBag.Title_link = "物流管理 > <a href=/Gox/ReturnGoods/Index_Mith>" + fun.Name + "</a> > 詳情";
            return View("Edit_Mith", item);

        }

        [MyAuthorize(Com = Competence.Update, function = "退貨資料")]
        public ActionResult Edit_Company(int Id = 0)
        {
            MithDataContext db = new MithDataContext();
            ReturnGoodsModel data = new ReturnGoodsModel();
            var fun = FunctionModel.Get_One(fun_id);

            var item = data.Get_One(Id);
            if (item == null)
            {
                return RedirectToAction("Index_Mith");
            }
            string CompanyTel = db.Company.FirstOrDefault(f => f.Name == item.Company_Name).Tel;
            if (!string.IsNullOrWhiteSpace(CompanyTel))
            {
                ViewData["CompanyTel"] = "0000000" + CompanyTel.Substring(CompanyTel.Length - 3, 3);
            }
            else
            {
                ViewData["CompanyTel"] = "0000000000";
            }

            db.Connection.Close();
            ViewBag.Title = "物流管理 > " + fun.Name + " > 詳情 ";
            ViewBag.Title_link = "物流管理 > <a href=/Gox/ReturnGoods/Index_Company>" + fun.Name + "</a> > 詳情";
            return View("Edit_Company", item);

        }

        [MyAuthorize(Com = Competence.Update, function = "退貨資料")]
        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(ReturnGoodsModel.ReturnGoodsShow item)
        {
            ReturnGoodsModel data = new ReturnGoodsModel();
            var fun = FunctionModel.Get_One(fun_id);
            string url = (string)Session["Url"];
            int user_id = Method.Get_UserId_Admin(Request.Cookies, Session);
            item.LastUserId = user_id;

            if (data.Update(item) <= 0)
            {
                ErrorRecordModel.Error_Record(Method.Get_UserId_Admin(Request.Cookies, Session), "ReturnGoods_5", Request.UserAgent, true, "資料新增失敗");
                TempData["err"] = "ReturnGoods_5";
                return RedirectToAction("Index");
            }

            TempData["FromAction"] = "儲存成功！";
            if (!string.IsNullOrWhiteSpace(url))
            {
                return Redirect(url);
            }
            else
            {
                return RedirectToAction("Index_Company");
            }
        }

        #endregion

        #region 刪除

        [MyAuthorize(Com = Competence.Delete, function = "退貨資料")]
        public ActionResult Delete(int item, int p = 1)
        {
            ReturnGoodsModel data = new ReturnGoodsModel();
            data.Delete(item);

            return RedirectToAction("Index", new { p = p });
        }

        [MyAuthorize(Com = Competence.Delete, function = "退貨資料")]
        [HttpPost]
        public ActionResult Delete(int[] item)
        {
            ReturnGoodsModel data = new ReturnGoodsModel();
            data.Delete(item);

            return RedirectToAction("Index");
        }

        #endregion

        #region Ajax
        public PartialViewResult Get_SelectGoosList(int[] Id, string GoodsAction)
        {
            MithDataContext db = new MithDataContext();
            List<ReturnGoodsModel.OrderDeatailShow> SelectGoosList = new List<ReturnGoodsModel.OrderDeatailShow>();
            try
            {

HuashanCRM/Areas/GoX/Views/ReturnGoods/Create.cshtml
@using Mith.Areas.GoX.Models
@model Mith.Areas.GoX.Models.ExpertModel.ExpertShow

@Scripts.Render("~/js/AdminExpertCreate")
@Styles.Render("~/css/Loading")
<script src="~/Scripts/plugin/Loading/jquery.isloading.min.js" type="text/javascript"></script>
<script src="" type="text/javascript"></script>

@using (Html.BeginForm("Create", "Expert", FormMethod.Post, new { @Id = "Form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Pic)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Pic, new { @type = "file", @accept = "image/*" })
            @Html.ValidationMessageFor(model => model.Pic)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Cover)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Cover, new { @type = "file", @accept = "image/*" })
            @Html.ValidationMessageFor(model => model.Cover)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Url)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Url, new { style="width:423px"})
            @Html.ValidationMessageFor(model => model.Url)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content, 6, 50, new { style = "resize: none;" })
            <br>
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <div class="editor-label">
            @Html.CheckBox("Enable", true) @Html.LabelFor(model => model.Enable)
        </div>

        <br>
        <p>
            <input type="submit" value="新增" id="save_sort" onclick="return Send()" />
        </p>
    </fieldset>

}

HuashanCRM/Areas/GoX/Views/ReturnGoods/Edit_Company.cshtml
@using Mith.Areas.GoX.Models
@using Mith.Models;
@model Mith.Areas.GoX.Models.ReturnGoodsModel.ReturnGoodsShow
@Scripts.Render("~/js/AdminReturnGoodsEdit")
@Styles.Render("~/css/AdminOrderEdit")
@Styles.Render("~/css/Loading")
<script src="~/Scripts/plugin/Loading/jquery.isloading.min.js" type="text/javascript"></script>
<!-- Datetimepicker2 -->
<script type="text/javascript" src="/Scripts/plugin/jquery.datetimepicker2.js"></script>
<link rel='stylesheet' type='text/css' href='/Content/themes/base/jquery.datetimepicker2.css' />

<style>
    #main-content .field-validation-error span {
        float: right;
        margin-right: 120px;
    }
</style>

<div id="overlay" style="display:none;"></div>
<div id="dialog" title="退貨明細說明">
    <div style="margin-top:10px;padding-left:5px;line-height:30px">
        <label>1. 當您勾選已收到貨時，無法再修物流編號、到貨日期</label><br>
        <label>2. 當你勾選同意退款時，無法再改為不同意退款</label><br>
    </div>
</div>
<div>
    @using (Html.BeginForm("Edit", "ReturnGoods", FormMethod.Post, new { @Id = "Form", @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.LogisticsType)

        <span style="font-weight:bold">退貨明細</span>
        <i class="fa fa-question-circle" onclick="OpenDialog_QA()"></i>
        <table id="OrderDetailTable" class="table table-striped" style="width:1150px">
            <thead>
                <tr>
                    <th id="item1" style="width:240px">訂單資訊</th>
                    <th id="item2" style="width:300px">退貨人</th>
                    <th id="item3" style="width:280px">退貨資訊</th>
                    <th id="item4" style="width:330px">備註</th>
                </tr>
            </thead>
            @*退貨方式 = 黑貓*@
            @if (Model.LogisticsType == 1)
            {
                <tbody>
                    <tr>
                        <td id="item1">
                            建立時間：@Model.CreateTime.ToString("yyyy/MM/dd HH:mm")<br>
                            訂單編號：@Model.SN<br>
                            退貨方式：@Model.LogisticsType_Name

                            @*關係訂單：@Model.RelativeSN*@
                        </td>
                        <td id="item2">
                            姓名：@Model.ReceiverName
                            <br>
                            電話：@Model.ReceiverTel
                            <br>
                            地址：@Model.ReceiverAddress
                            <br>
                            取件時段：@Model.ReceiveTimeRange_Name
                        </td>
                        <td id="item3">
                            物流編號：
                            @if (!string.IsNullOrWhiteSpace(Model.LogisticsSN))
                            {
                                @Html.TextBoxFor(model => model.LogisticsSN, new { style = "margin-bottom: 10px;width: 140px;vertical-align: top;height: 28px;" })
                                <text>&emsp;&emsp;</text>
                                @Html.ValidationMessageFor(model => model.LogisticsSN)
                            }
                            else
                            {
                                @Html.TextBoxFor(model => model.LogisticsSN, new { style = "width:140px;vertical-align: middle;" })
                                <text>&emsp;&emsp;</text>
                                @Html.ValidationMessageFor(model => model.LogisticsSN)
                            }
                            <br>
                            退貨時間：@Model.CreateTime.ToString("yyyy/MM/dd HH:mm")<br>
                            @if (!string.IsNullOrWhiteSpace(@Model.LastUser_Name))
                            {
                                <text>更新人員：@Model.LastUser_Name </text>
                                <br>
                            }
                            已收到貨：@Html.CheckBoxFor(model => model.ReturnGoods)<br>
                            <span id="span_ReturnGoods" style="display:none;margin-top:4px">
                                到貨時間：
                                @Html.TextBoxFor(model => model.ReturnGoodsTime, "{0:yyyy/MM/dd HH:mm}", new { style = "margin-bottom: 10px;width: 140px;vertical-align: top;height: 28px;" })
                                <span class="Valid" id="ReturnGoodsTime_Valid">必填欄位</span>
                                <br>
                                同意退款：@Html.CheckBoxFor(model => model.AgreeRefund)
                            </span>
                        </td>
                        <td id="item4">
                            @if (!string.IsNullOrWhiteSpace(Model.Remark))
                            {
                                @Model.Remark
                            }
                            else
                            {
                                <text>無</text>
                            }
                        </td>
                    </tr>
                </tbody>
            }
            @*退貨方式 = 7-11*@
            else
            {
                <tbody>
                    <tr>
                        <td id="item1">
                            建立時間：@Model.CreateTime.ToString("yyyy/MM/dd HH:mm")<br>
                            訂單編號：@Model.SN<br>
                            退貨方式：@Model.LogisticsType_Name
                        </td>
                        <td id="item2">
                            7-11
                        </td>
                        <td id="item3">
                            物流編號：
                            @Html.HiddenFor(model => model.LogisticsSN)
                            @Model.PackageSN
                            <br>
                            退貨時間：@Model.CreateTime.ToString("yyyy/MM/dd HH:mm")<br>
                            @if (!string.IsNullOrWhiteSpace(@Model.LastUser_Name))
                            {
                                <text>更新人員：@Model.LastUser_Name </text>
                                <br>
                            }
                            已收到貨：
                            @*退回門市中*@
                            @if (@Model.OrderDetailList[0].LogisticsStatus == 7)
                            {
                                @Html.CheckBoxFor(model => model.ReturnGoods, new { @disabled = "disabled" })
                            }
                            else
                            {
                                @Html.CheckBoxFor(model => model.ReturnGoods)
                            }
                            <br>
                            <span id="span_ReturnGoods" style="display:none;margin-top:4px">
   
                                同意退款：@Html.CheckBoxFor(model => model.AgreeRefund)
                            </span>
                        </td>
                        <td id="item4">
                            @if (!string.IsNullOrWhiteSpace(Model.Remark))
                            {
                                @Model.Remark
                            }
                            else
                            {
                                <text>無</text>
                            }
                        </td>
                    </tr>
                </tbody>
            }
        </table>
        <br>
        <span style="font-weight:bold">商品明細</span>
        <table id="GoodsDetailTable" class="table table-striped" style="width:1150px;margin-top:5px">
            <thead>
                <tr>
                    <th id="item1" style="width:320px">名稱</th>
                    <th id="item2" style="width:140px">類別</th>
                    <th id="item2" style="width:60px">顏色</th>
                    <th id="item3" style="width:90px">物流狀態</th>
                    <th id="item5" style="width:160px">廠商</th>
                    <th id="item6" style="width:60px">尺寸</th>
                    <th id="item7" style="width:60px">數量</th>
                    <th id="item8" style="width:70px">單價</th>
                    <th id="item9" style="width:70px">小計</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.OrderDetailList.Count(); i++)
                {
                    <tr>
                        <td id="item1" style="width:320px;text-align:left!important;padding-left:5px">
                            【@Model.OrderDetailList[i].Goods_SN】 @Model.OrderDetailList[i].Goods_Name

                        </td>
                        <td id="item2" style="width:140px;text-align:center">
                            @Model.OrderDetailList[i].Goods_TypeName
                        </td>
                        <td id="item2" style="width:60px;text-align:center">
                            @Model.OrderDetailList[i].Goods_ColorName
                        </td>
                        <td id="item3" style="width:90px;text-align:center">
                            @if (@Model.OrderDetailList[i].LogisticsStatus > 0)
                            {
                                <span style="color:#00AA00">@Model.OrderDetailList[i].LogisticsStatus_Name</span>
                            }
                            else
                            {
                                <span style="color:red">@Model.OrderDetailList[i].LogisticsStatus_Name</span>
                            }
                        </td>
                        <td id="item5" style="width:160px;text-align:center">
                            @Model.OrderDetailList[i].Company_Name
                        </td>
                        <td id="item6" style="width:60px;text-align:center">
                            @Model.OrderDetailList[i].BuySize
                        </td>
                        <td id="item7" style="width:60px;text-align:center">
                            @Model.OrderDetailList[i].BuyQuantity
                        </td>
                        <td id="item8" style="width:70px;text-align:center">
                            @Model.OrderDetailList[i].BuyPrice
                        </td>
                        <td id="item9" style="width:70px;text-align:center">
                            @Model.OrderDetailList[i].BuyTotal.ToString("N0")
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        if (@Model.AgreeRefund == false)
        {
            <span style=" padding-top: 5px;float:left">
                <input type="submit" value="儲存" id="save_sort" onclick="return Send()" />
            </span>
        }
    }
</div>

<span style="float:right;padding-right:50px; padding-top:5px;"><b>總計：$@Model.BuyTotal.ToString("N0")</b></span>
<br><br>

HuashanCRM/Areas/GoX/Views/ReturnGoods/Edit_Mith.cshtml
@using Mith.Areas.GoX.Models
@using Mith.Models;
@model Mith.Areas.GoX.Models.ReturnGoodsModel.ReturnGoodsShow
@Scripts.Render("~/js/AdminReturnGoodsEdit")
@Styles.Render("~/css/AdminOrderEdit")
@Styles.Render("~/css/Loading")
<script src="~/Scripts/plugin/Loading/jquery.isloading.min.js" type="text/javascript"></script>

<div>
    <span style="font-weight:bold">退貨明細</span>
    <table id="OrderDetailTable" class="table table-striped" style="width:1150px">
        <thead>
            <tr>
                <th id="item1" style="width:240px">訂單資訊</th>
                <th id="item2" style="width:300px">退貨人</th>
                <th id="item3" style="width:280px">退貨資訊</th>
                <th id="item4" style="width:330px">備註</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td id="item1">
                    建立時間：@Model.CreateTime.ToString("yyyy/MM/dd HH:mm")<br>
                    訂單編號：@Model.SN<br>
                    退貨方式：@Model.LogisticsType_Name
                    @*關係訂單：@Model.RelativeSN*@
                </td>
                <td id="item2">
                    @if (Model.LogisticsType == 1)
                    {
                        <text>

                            姓名：@Model.ReceiverName
                            <br>
                            電話：@Model.ReceiverTel
                            <br>

                            地址：@Model.ReceiverAddress
                            <br>
                            取件時段：@Model.ReceiveTimeRange_Name
                        </text>
                    }
                    else
                    {
                        <text>7-11</text>
                    }
                </td>
                <td id="item3">
                    物流編號：
                    @if (!string.IsNullOrWhiteSpace(Model.PackageSN))
                    {
                        @Model.PackageSN
                    }
                    else
                    {
                        <a href="http://www.t-cat.com.tw/inquire/TraceDetail.aspx?ReturnUrl=Trace.aspx&BillID=@Model.LogisticsSN" target="_blank">@Model.LogisticsSN</a>
                    }
                    <br>
                    退貨時間：@Model.CreateTime.ToString("yyyy/MM/dd HH:mm")
                    <br>
                    退貨廠商：@Model.Company_Name
                    <br>
                    已收到貨：
                    @if (Model.ReturnGoods)
                    {
                        <span style="color:#00AA00">是</span>
                        <br>
                        <text>到貨時間：</text>
                        if (Model.LogisticsType == 1)
                        {
                            if (!string.IsNullOrWhiteSpace(Model.ReturnGoodsTime.ToString()))
                            {
                                <text>@Model.ReturnGoodsTime.Value.ToString("yyyy/MM/dd HH:mm")</text>
                            }
                            else
                            {
                                <text>無</text>
                            }
                        }
                        else
                        {
                            if (!string.IsNullOrWhiteSpace(Model.ArriveInTime.ToString()))
                            {
                                <text>@Model.ArriveInTime.Value.ToString("yyyy/MM/dd HH:mm")</text>
                            }
                            else
                            {
                                <text>無</text>
                            }
                        }
                        <br>
                        <text>同意退款：</text>
                        if (Model.AgreeRefund)
                        {
                            <span style="color:#00AA00">是</span>
                        }
                        else
                        {
                            <span style="color:red">否</span>
                        }
                    }
                    else
                    {
                        <span style="color:red">否</span>
                    }
                </td>
                <td id="item4">
                    @if (!string.IsNullOrWhiteSpace(Model.Remark))
                    {
                        @Model.Remark
                    }
                    else
                    {
                        <text>無</text>
                    }
                </td>
            </tr>
        </tbody>
    </table>
    <br>
    <span style="font-weight:bold">商品明細</span>
    @using (Ajax.BeginForm("Get_SelectGoosList", "Order", new AjaxOptions { UpdateTargetId = "UpdateArea", HttpMethod = "GET" }, new { id = "ReturnGoodsForm" }))
    {
        <table id="GoodsDetailTable" class="table table-striped" style="width:1150px;margin-top:5px">
            <thead>
                <tr>
                    <th id="item1" style="width:320px">名稱</th>
                    <th id="item2" style="width:140px">類別</th>
                    <th id="item2" style="width:60px">顏色</th>
                    <th id="item3" style="width:90px">物流狀態</th>
                    <th id="item5" style="width:160px">廠商</th>
                    <th id="item6" style="width:60px">尺寸</th>
                    <th id="item7" style="width:60px">數量</th>
                    <th id="item8" style="width:70px">單價</th>
                    <th id="item9" style="width:70px">小計</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.OrderDetailList.Count(); i++)
                {
                    <tr>
                        <td id="item1" style="width:320px;text-align:left!important;padding-left:5px">
                            【@Model.OrderDetailList[i].Goods_SN】
                            @Model.OrderDetailList[i].Goods_Name
                        </td>
                        <td id="item2" style="width:140px;text-align:center">
                            @Model.OrderDetailList[i].Goods_TypeName
                        </td>
                        <td id="item2" style="width:60px;text-align:center">
                            @Model.OrderDetailList[i].Goods_ColorName
                        </td>
                        <td id="item3" style="width:90px;text-align:center">
                            @if (@Model.OrderDetailList[i].LogisticsStatus > 0)
                            {
                                <span style="color:#00AA00">@Model.OrderDetailList[i].LogisticsStatus_Name</span>
                            }
                            else
                            {
                                <span style="color:red">@Model.OrderDetailList[i].LogisticsStatus_Name</span>
                            }
                        </td>
                        <td id="item5" style="width:160px;text-align:center">
                            @Model.OrderDetailList[i].Company_Name
                        </td>
                        <td id="item6" style="width:60px;text-align:center">
                            @Model.OrderDetailList[i].BuySize
                        </td>
                        <td id="item7" style="width:60px;text-align:center">
                            @Model.OrderDetailList[i].BuyQuantity
                        </td>
                        <td id="item8" style="width:70px;text-align:center">
                            @Model.OrderDetailList[i].BuyPrice
                        </td>
                        <td id="item9" style="width:70px;text-align:center">
                            @Model.OrderDetailList[i].BuyTotal.ToString("N0")
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
<span style="float:right;padding-right:50px; padding-top:5px;"><b>總計：$@Model.BuyTotal.ToString("N0")</b></span>
<br><br>