HuashanCRM/Areas/GoX/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using System.Web.UI.DataVisualization.Charting;
using System.Drawing;
using System.Text;
using System.IO;
using Mith.Models;
using Mith.Areas.GoX.Models;

namespace Mith.Areas.GoX.Controllers
{
    public class CompanyController : CategoryController
    {
        int fun_id = 5;

        #region 首頁
        [RoleAuthorize(Role = "亞設人員")]
        [MyAuthorize(Com = Competence.Read, function = "廠商資料")]
        public ActionResult Index(string keyword = "", int Search_Collaborate = 0, int Search_Type = -1, int Search_GoodsKind = 0, DateTime? CreateTime_St = null, DateTime? CreateTime_End = null, int p = 1, int show_number = 10)
        {
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);
            string get = "";
            if (keyword != "")
            {
                data.Keyword = keyword;
                ViewData["keyword"] = keyword;
                get += Method.Get_URLGet("keyword", keyword);
            }
            if (Search_Collaborate != 0)
            {
                data.Search_Collaborate = Search_Collaborate;
                ViewData["Search_Collaborate"] = Search_Collaborate;
                get += Method.Get_URLGet("Search_Collaborate", Search_Collaborate.ToString());
            }
            if (Search_Type != -1)
            {
                data.Search_Type = Search_Type;
                ViewData["Search_Type"] = Search_Type;
                get += Method.Get_URLGet("Search_Type", Search_Type.ToString());
            }

            if (Search_GoodsKind != 0)
            {
                data.Search_GoodsKind = Search_GoodsKind;
                ViewData["Search_GoodsKind"] = Search_GoodsKind;
                get += Method.Get_URLGet("Search_GoodsKind", Search_GoodsKind.ToString());
            }
            if (CreateTime_St != null)
            {
                data.CreateTime_St = CreateTime_St;
                ViewData["CreateTime_St"] = CreateTime_St;
                get += Method.Get_URLGet("CreateTime_St", CreateTime_St.Value.ToString("yyyy/MM/dd HH:mm:ss"));
            }
            if (CreateTime_End != null)
            {
                data.CreateTime_End = CreateTime_End;
                ViewData["CreateTime_End"] = CreateTime_End;
                get += Method.Get_URLGet("CreateTime_End", CreateTime_End.Value.ToString("yyyy/MM/dd HH:mm:ss"));
            }

            ViewBag.Title = fun.Name;
            ViewBag.Title_link = "廠商管理 > <a href=\"\">" + fun.Name + "</a>";

            ViewData["p"] = p;
            ViewData["page"] = data.Get_Page(p, show_number);
            ViewData["number"] = show_number;
            ViewData["get"] = get;
            Session["Url"] = Request.Url.AbsoluteUri;
            Session["item"] = null;
            return View(data.Get_Data(p, show_number));
        }

        #endregion

        #region 新增

        [MyAuthorize(Com = Competence.Insert, function = "廠商資料")]
        public ActionResult Create_Step1()
        {
            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);

            ViewBag.Title = "廠商管理 > " + fun.Name + " > 新增 (基本資訊)";
            ViewBag.Title_link = "廠商管理 > <a href=/GoX/Company/Index>" + fun.Name + "</a> > 新增 (基本資訊)";
            ViewBag.c_title = fun.Name;
            db.Connection.Close();
            return View();
        }

        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create_Step1(CompanyModel.CompanyShow item)
        {

            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);

            item.Id = db.Company.OrderByDescending(o => o.Id).FirstOrDefault() != null ? db.Company.OrderByDescending(o => o.Id).FirstOrDefault().Id + 1 : 1;
            db.Connection.Close();
            Session["item"] = item;
            return RedirectToAction("Create_Step2");
        }

        [MyAuthorize(Com = Competence.Insert, function = "廠商資料")]
        public ActionResult Create_Step2(CompanyModel.CompanyShow item)
        {
            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);
            item = Session["item"] as CompanyModel.CompanyShow;
            if (item == null)
            {
                return RedirectToAction("Create_Step1");
            }
            ViewBag.Title = "廠商管理 > " + fun.Name + " >  新增 (合作類別 / 狀態)";
            ViewBag.Title_link = "廠商管理 > <a href=/GoX/Company/Index>" + fun.Name + "</a> >  新增 (合作類別 / 狀態)";
            ViewBag.c_title = fun.Name;

            db.Connection.Close();
            return View(item);
        }

        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create_Step2(CompanyModel.CompanyShow item, string post = "")
        {

            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);

            Session["item"] = item;
            return RedirectToAction("Create_Step3");
        }


        [MyAuthorize(Com = Competence.Insert, function = "廠商資料")]
        public ActionResult Create_Step3(CompanyModel.CompanyShow item)
        {
            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);
            item = Session["item"] as CompanyModel.CompanyShow;
            if (item == null)
            {
                return RedirectToAction("Create_Step1");
            }
            ViewBag.Title = "廠商管理 > " + fun.Name + " >  新增 (帳務資料)";
            ViewBag.Title_link = "廠商管理 > <a href=/GoX/Company/Index>" + fun.Name + "</a> >  新增 (帳務資料)";
            ViewBag.c_title = fun.Name;

            db.Connection.Close();
            return View(item);
        }

        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create_Step3(CompanyModel.CompanyShow item, string IsPost = "")
        {

            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);

            if (ModelState.IsValid)
            {
                if (data.Insert(item) <= 0)
                {
                    ErrorRecordModel.Error_Record(Method.Get_UserId_Admin(Request.Cookies, Session), "Company_2", Request.UserAgent, true, "資料新增失敗");
                    TempData["err"] = "Company_2，資料新增失敗";
                }
            }
            else
            {
                ErrorRecordModel.Error_Record(Method.Get_UserId_Admin(Request.Cookies, Session), "Company_3", Request.UserAgent, true, "資料新增失敗");
                TempData["err"] = "Company_3，資料新增失敗";
            }
            db.Connection.Close();
            TempData["FromAction"] = "新增成功！";
            Session["item"] = null;
            return RedirectToAction("Index");
        }

        #endregion

        #region 編輯

        [MyAuthorize(Com = Competence.Update, function = "廠商資料")]
        public ActionResult Edit_Step1(int id = 0)
        {
            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);

            ViewBag.Title = "廠商管理 > " + fun.Name + " > 編輯 (基本資訊)";
            ViewBag.Title_link = "廠商管理 > <a href=/GoX/Company/Index>" + fun.Name + "</a> > 編輯 (基本資訊)";
            ViewBag.c_title = fun.Name;

            var item = data.Get_One_Step1(id);
            if (item == null)
            {
                return RedirectToAction("Create_Step1");
            }
            db.Connection.Close();
            return View(item);
        }

        [MyAuthorize(Com = Competence.Update, function = "廠商資料")]
        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit_Step1(CompanyModel.CompanyShow item)
        {
            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            string url = (string)Session["Url"];

            int user_id = Method.Get_UserId_Admin(Request.Cookies, Session);
            item.LastUserId = user_id;

            if (data.Update_Step1(item) <= 0)
            {
                ErrorRecordModel.Error_Record(Method.Get_UserId_Admin(Request.Cookies, Session), "Company_5", Request.UserAgent, true, "資料新增失敗");
                TempData["err"] = "Company_5";
                return RedirectToAction("Index");
            }
            db.Connection.Close();
            TempData["FromAction"] = "儲存成功！";
            if(!string.IsNullOrWhiteSpace(url))
            {
                return Redirect(url);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [MyAuthorize(Com = Competence.Update, function = "廠商資料")]
        public ActionResult Edit_Step2(int id = 0)
        {
            MithDataContext db = new MithDataContext();
            CompanyModel data = new CompanyModel();
            var fun = FunctionModel.Get_One(fun_id);

            ViewBag.Title = "廠商管理 > " + fun.Name + " >  編輯 (合作類別 / 狀態)";
            ViewBag.Title_link = "廠商管理 > <a href=/GoX/Company/Index>" + fun.Name + "</a> >  編輯 (合作類別 / 狀態)";
            ViewBag.c_title = fun.Name;

            var item = data.Get_One_Step2(id);
            if (item == null)
            {
                return RedirectToAction("Create_Step1");
            }
            db.Connection.Close();
            return View(item);
        }

HuashanCRM/Areas/GoX/Views/Company/Create_Step1.cshtml
@using Mith.Areas.GoX.Models
@model Mith.Areas.GoX.Models.CompanyModel.CompanyShow
@{
   

}
@Scripts.Render("~/js/AdminCompanyCreate")

@using (Html.BeginForm("Create_Step1", "Company", FormMethod.Post, new { @Id = "Form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset class="confirm2" style="width: 480px;padding-left: 25px;">
        <legend>基本資訊</legend>
        <table style="background-color: transparent;">
            <tr>
                <td style="width: 240px;">
                    <div class="">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Name)
                        <br>
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </td>
                <td style="vertical-align:top">
                    <div class="">
                        @Html.LabelFor(model => model.TaxId)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.TaxId)
                        @Html.ValidationMessageFor(model => model.TaxId)
                    </div>

                </td>
            </tr>
            <tr>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Tel)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Tel)
                        <br>
                        @Html.ValidationMessageFor(model => model.Tel)
                    </div>
                </td>
                <td style="vertical-align:top!important">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Fax)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Fax)
                        @Html.ValidationMessageFor(model => model.Fax)
                    </div>

                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Address)
                    </div>
                    <div class="editor-field">
                        @Html.Raw(Html.DropDownListFor(model => model.CityId, Mith.Models.CityArea.Get_City_Select(0, false), new { style = "width:80px;cursor:pointer" }))
                        @Html.Raw(Html.DropDownListFor(model => model.AreaId, Mith.Models.CityArea.Get_Area_Select(0, 0, false), new { style = "width:80px;cursor:pointer" }))
                        @Html.TextBoxFor(model => model.Address, new { style = "width: 272px;" })
                        @Html.ValidationMessageFor(model => model.Address)

                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.BossName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.BossName)
                        @Html.ValidationMessageFor(model => model.BossName)
                    </div>
                </td>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.BossIdentityCard)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.BossIdentityCard)
                        @Html.ValidationMessageFor(model => model.BossIdentityCard)
                    </div>

                </td>
            </tr>

        </table>
        <br>
    </fieldset>
    <br>  
    <br>
    <fieldset class="confirm2" style="width: 480px;padding-left: 25px;">
        <legend>聯絡窗口</legend>
        <table style="background-color: #f1f2f7 ">
            <tr>
                <td style="width:60%">
                    <div class="">
                        @Html.LabelFor(model => model.ContactName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ContactName)
                        @Html.ValidationMessageFor(model => model.ContactName)
                    </div>
                </td>
                <td>
                    <div class="">
                        @Html.LabelFor(model => model.ContactTel)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ContactTel)
                        @Html.ValidationMessageFor(model => model.ContactTel)
                    </div>

                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ContactEmail)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ContactEmail, new { style = "width:100%" })
                        <br>
                        @Html.ValidationMessageFor(model => model.ContactEmail)                      
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        <input type="submit" value="下一步" id="save_sort" onclick="return Step1_Send()" />
                    </div>
                </td>
            </tr>
        </table>
        <br>

    </fieldset>
}

HuashanCRM/Areas/GoX/Views/Company/Create_Step2.cshtml
@using Mith.Areas.GoX.Models
@using Mith.Models
@model Mith.Areas.GoX.Models.CompanyModel.CompanyShow
@{
    List<Mith.Models.Category> TypeList = new List<Mith.Models.Category>();
    TypeList = Method.GetCategoryList(5, "Type");

    List<Mith.Models.Category> GoodsKindList = new List<Mith.Models.Category>();
    GoodsKindList = Method.GetCategoryList(5, "GoodsKind");
}
@Scripts.Render("~/js/AdminCompanyCreate")


@using (Html.BeginForm("Create_Step2", "Company", FormMethod.Post, new { @Id = "Form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.GoodsKind)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Name)
    @Html.HiddenFor(model => model.TaxId)
    @Html.HiddenFor(model => model.Tel)
    @Html.HiddenFor(model => model.Fax)
    @Html.HiddenFor(model => model.BossName)
    @Html.HiddenFor(model => model.BossIdentityCard)
    @Html.HiddenFor(model => model.CityId)
    @Html.HiddenFor(model => model.AreaId)
    @Html.HiddenFor(model => model.Address)
    @Html.HiddenFor(model => model.ContactName)
    @Html.HiddenFor(model => model.ContactTel)
    @Html.HiddenFor(model => model.ContactEmail)
    @Html.Hidden("Check_SN", "False")    //判斷有沒有按驗證序號
    <fieldset>
        <table style="background-color: transparent;">
            <tr>
                <td style="width: 260px;">
                    <div class="">
                        @Html.LabelFor(model => model.ContractDate)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ContractDate, "{0:yyyy/MM/dd HH:mm}", new { @class = "date_search" })
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ManagementFee)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ManagementFee, new { placeholder = "每筆" })
                        @Html.ValidationMessageFor(model => model.ManagementFee)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ArtEditorCost)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ArtEditorCost, new { placeholder = "元 / 件" })
                        @Html.ValidationMessageFor(model => model.ArtEditorCost)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.FreightFee)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.FreightFee, new { placeholder = "元 / 次" })
                        @Html.ValidationMessageFor(model => model.FreightFee)
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Type)
                    </div>
                    <div class="editor-field">
                        @for (int i = 0; i < TypeList.Count(); i++)
                        {
                            <input type="radio" name="Type" value="@TypeList[i].Number" @if (i == 0) { <text> checked </text>      }>
                            @TypeList[i].Name<text>(@TypeList[i].Number)&emsp;</text>

                        }
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.SN)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.SN, new { style = "width: 50px;text-align:center", @id = "SN" })
                        <input type="button" value="驗證" onclick="return Check_SN_Click()">
                        @Html.ValidationMessageFor(model => model.SN)
                        <span class="Valid" id="SN_Valid"></span>
                    </div>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.GoodsKind)
                    </div>
                    <div class="editor-field">
                        @for (int i = 0; i < GoodsKindList.Count(); i++)
                        {
                            <input type="checkbox" name="GoodsKindList" id="GoodsKindList" value="@GoodsKindList[i].Number">
                            @GoodsKindList[i].Name<text>&emsp;</text>

                        }
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.CheckBox("Collaborate", true) @Html.LabelFor(model => model.Collaborate)
                    </div>
                    <div class="editor-field">
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        <input type="submit" value="下一步" id="save_sort" onclick="return Step2_Send()" />
                    </div>
                </td>
            </tr>
        </table>
    </fieldset>

}

HuashanCRM/Areas/GoX/Views/Company/Create_Step3.cshtml
@using Mith.Areas.GoX.Models
@model Mith.Areas.GoX.Models.CompanyModel.CompanyShow
@Scripts.Render("~/js/AdminCompanyCreate")
@Styles.Render("~/css/Loading")
<script src="~/Scripts/plugin/Loading/jquery.isloading.min.js" type="text/javascript"></script>

@using (Html.BeginForm("Create_Step3", "Company", FormMethod.Post, new { @Id = "Form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.GoodsKind)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Name)
    @Html.HiddenFor(model => model.TaxId)
    @Html.HiddenFor(model => model.Tel)
    @Html.HiddenFor(model => model.Fax)
    @Html.HiddenFor(model => model.BossName)
    @Html.HiddenFor(model => model.BossIdentityCard)
    @Html.HiddenFor(model => model.CityId)
    @Html.HiddenFor(model => model.AreaId)
    @Html.HiddenFor(model => model.Address)
    @Html.HiddenFor(model => model.ContactName)
    @Html.HiddenFor(model => model.ContactTel)
    @Html.HiddenFor(model => model.ContactEmail)
    @Html.HiddenFor(model => model.ContractDate)
    @Html.HiddenFor(model => model.ManagementFee)
    @Html.HiddenFor(model => model.ArtEditorCost)
    @Html.HiddenFor(model => model.FreightFee)
    @Html.HiddenFor(model => model.Type)
    @Html.HiddenFor(model => model.SN)
    @Html.HiddenFor(model => model.GoodsKind)
    @Html.HiddenFor(model => model.Collaborate)

    <fieldset class="confirm2" style="width: 480px;padding-left: 25px;">
        <legend>帳務處理</legend>
        <table style="background-color: transparent;">
            <tr>
                <td style="width: 240px;">
                    <div class="">
                        @Html.LabelFor(model => model.AccountingName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountingName)
                        @Html.ValidationMessageFor(model => model.AccountingName)
                    </div>
                </td>
                <td>
                    <div class="">
                        @Html.LabelFor(model => model.AccountingTel)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountingTel)
                        @Html.ValidationMessageFor(model => model.AccountingTel)
                    </div>

                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.AccountingEmail)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountingEmail, new { style = "width:420px" })
                        @Html.ValidationMessageFor(model => model.AccountingEmail)
                    </div>
                </td>
            </tr>
        </table>
        <br>
    </fieldset>
    <br>
    <br>
    <fieldset class="confirm2" style="width: 480px;padding-left: 25px;">
        <legend>貨款撥付</legend>
        <table style="background-color: transparent;">
            <tr>
                <td style="width: 240px;">
                    <div class="">
                        @Html.LabelFor(model => model.BankName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.BankCode, new { style = "width:40px;text-align: center;", placeholder = "001" })
                        @Html.ValidationMessageFor(model => model.BankCode)
                        @Html.TextBoxFor(model => model.BankName, new { style = "width:165px;", placeholder = " XX銀行" })
                        @Html.ValidationMessageFor(model => model.BankName)
                    </div>
                </td>
                <td>
                    <div class="">
                        @Html.LabelFor(model => model.Account)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Account)
                        @Html.ValidationMessageFor(model => model.Account)
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.AccountName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountName)
                        @Html.ValidationMessageFor(model => model.AccountName)
                    </div>
                </td>
                <td>
                    <div class="editor-label">
                        　
                    </div>
                    <div class="editor-field">
                        <input type="submit" value="新增" id="save_sort" onclick="return Step3_Send()" />
                    </div>
                </td>
            </tr>
        </table>
        <br>
    </fieldset>
}

HuashanCRM/Areas/GoX/Views/Company/Edit_Step3.cshtml
@using Mith.Areas.GoX.Models
@model Mith.Areas.GoX.Models.CompanyModel.CompanyShow
@Scripts.Render("~/js/AdminCompanyEdit")
@Styles.Render("~/css/Loading")
<script src="~/Scripts/plugin/Loading/jquery.isloading.min.js" type="text/javascript"></script>

@using (Html.BeginForm("Edit_Step3", "Company", FormMethod.Post, new { @Id = "Form", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <div class="">
        廠商
    </div>
    <div class="editor-field">
        【@Html.DisplayFor(model => model.SN)】 @Html.DisplayFor(model => model.Name)
        <br>
    </div>

    <br>
    <fieldset class="confirm2" style="width: 480px;padding-left: 25px;">

        <legend>帳務處理</legend>
        <table style="background-color: transparent;">

            <tr>
                <td style="width: 240px;">
                    <div class="">
                        @Html.LabelFor(model => model.AccountingName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountingName)
                        @Html.ValidationMessageFor(model => model.AccountingName)
                    </div>
                </td>
                <td>
                    <div class="">
                        @Html.LabelFor(model => model.AccountingTel)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountingTel)
                        @Html.ValidationMessageFor(model => model.AccountingTel)
                    </div>

                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.AccountingEmail)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountingEmail, new { style = "width:420px" })
                        @Html.ValidationMessageFor(model => model.AccountingEmail)
                    </div>
                </td>
            </tr>
        </table>
        <br>
    </fieldset>
    <br>
    <br>
    <fieldset class="confirm2" style="width: 480px;padding-left: 25px;">
        <legend>貨款撥付</legend>
        <table style="background-color: transparent;">
            <tr>
                <td style="width: 240px;">
                    <div class="">
                        @Html.LabelFor(model => model.BankName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.BankCode, new { style = "width:40px;text-align: center;", placeholder = "001" })
                        @Html.ValidationMessageFor(model => model.BankCode)
                        @Html.TextBoxFor(model => model.BankName, new { style = "width:165px;", placeholder = " XX銀行" })
                        @Html.ValidationMessageFor(model => model.BankName)
                    </div>
                </td>
                <td>
                    <div class="">
                        @Html.LabelFor(model => model.Account)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Account)
                        @Html.ValidationMessageFor(model => model.Account)
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.AccountName)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.AccountName)
                        @Html.ValidationMessageFor(model => model.AccountName)
                    </div>
                </td>
            </tr>
            <tr>
                <td style="width:60%">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.CreateTime)
                    </div>
                    <div class="editor-field">
                        @Model.CreateTime.Value.ToString("yyyy/MM/dd HH:mm")
                    </div>
                </td>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.UpdateTime)
                    </div>
                    <div class="editor-field">
                        @Model.UpdateTime.Value.ToString("yyyy/MM/dd HH:mm")
                    </div>

                </td>
            </tr>
            <tr>
                <td style="width:60%">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.LastUser_Name)
                    </div>
                    <div class="editor-field">
                        @Html.DisplayFor(model => model.LastUser_Name)
                    </div>
                </td>
                <td>
                    <div class="editor-label">
                        <input type="submit" value="儲存" id="save_sort" onclick="return Step3_Send()" />
                    </div>
                </td>
            </tr>
        </table>
        <br>
    </fieldset>
}